### ISSUE TITLE
Problem with AR enum: ArgumentError (You tried to define an enum named "mediatype" on the model "MediaItem", but this will generate a instance method "mediatype=", which is already defined by another enum.)

### ISSUE THREAD

**Issue by olegantonyan** [catprintlabs/reactive-record#14]
Hi!
I just installed reactrb with --all and have a problem.
With reactive-record installed I get this error:

```
ArgumentError (You tried to define an enum named "mediatype" on the model "MediaItem", but this will generate a instance method "mediatype=", which is already defined by another enum.):
  app/models/media_item.rb:9:in `<class:MediaItem>'
  app/models/media_item.rb:1:in `<top (required)>'
  app/controllers/media_items_controller.rb:10:in `index'
```

``` ruby
#  app/models/media_item.rb
class MediaItem < ActiveRecord::Base
  ... 
  enum mediatype: %w(background advertising)
```

But, if after server start I load some other page (not related to MediaItem model), then everything work. Something wrong with models load (order or I don't know). Actual name of the enum doesn't matter.

**Comment by catmando** [comment]
That is odd. 

While reactive-record does not yet support enums out of the box, this is not the expected failure mode.  To be sure I just did a little smoke testing, and I do not get any problems unless I try to access the record on the client, and then I get errors in the browser, not in the server as you have.

I assume here you just ran the installer, and are now trying to run the app which was working before, but now breaks.  Is that correct?

If at all possible could you give me read access to the repo, and I will try it out on my machine?  If not then please try these steps:

1) remove reactive-record gem.

Does problem go away?  If so let me know, and I will go from there.

2) If the problem does not go away then (when gem is removed) please put it back and find these two lines (added by the installer) in application.rb and comment them out:

``` ruby
      config.autoload_paths += %W(#{config.root}/app/react/models) 
      config.eager_load_paths += %W(#{config.root}/app/react/models)
```

Does that make the problem go away (if so that is very weird, but let me know.)

**Comment by olegantonyan** [comment]
@catmando  thanks for quick response!

> I assume here you just ran the installer, and are now trying to run the app which was working before, but now breaks. Is that correct?

Yep

> 1) remove reactive-record gem.
> Does problem go away?

Yep

I've created fresh new rails 4.2.5.1 app https://github.com/olegantonyan/test_reactive_record and it reproduces there. Interestingly, is this app it fails only first time after server start. Consequent reload works. Maybe spring is in charge (I don't use in original app). But the error is still there.
Steps I did:

```
rails _4.2.5.1_ new test_reactive_record
bundle exec rails g scaffold post body:string status:integer
add enum to model and select to view
create couple posts
add gem "reactive_rails_generator"
bundle update
bundle exec rails g reactrb:install --all
bundle exec rails g reactrb:component Posts::Show
add render_component to PostsController#show
restart the server
visit localhost:3000/posts
```

**Comment by catmando** [comment]
ill have a look asap.. thanks for the details

**Comment by catmando** [comment]
Okay this is also set... just update to latest gem (v 0.7.39)

Also added support for ActiveRecord enums

**Comment by olegantonyan** [comment]
Briliant! Thank you!
